# docker-compose.yml
version: '3.8'

services:
  ocr-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FIREBASE_CREDENTIALS=firebase-split-service-key.json
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
    volumes:
      - ./firebase-split-service-key.json:/app/firebase-split-service-key.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"